import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {flex: 1, width: '100%'},
  headerContainer: {
    display: 'flex',
    flexDirection: 'row',
  },
  resultContainer: {justifyContent: 'center', width: '80%'},
  txtResult: {fontSize: 20, marginLeft: 10},
  btnRestart: {
    backgroundColor: 'grey',
    height: 40,
    width: 70,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  imgContainer: {
    flex: 0.7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textContainer: {
    position: 'absolute',
    bottom: 10,
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  txtAlphabets: {
    width: 40,
    height: 40,
    fontSize: 50,
    borderWidth: 1,
    justifyContent: 'center',
    fontWeight: 'bold',
    borderTopColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
  },
  keysContainer: {
    flex: 0.3,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowKeys: {flexDirection: 'row'},
  btnKeys: {
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderColor: 'grey',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 2,
    borderRadius: 20,
  },
  textKeys: {fontSize: 20},
  modalContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    backgroundColor: 'white',
    flex: 0.4,
    borderRadius: 10,
    width: 300,
  },
  modalHeader: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtModalTitle: {fontSize: 20},
  contentContainerStyle: {height: 44},
  rowOptions: {
    backgroundColor: 'grey',
    margin: 5,
    padding: 5,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  txtList: {fontSize: 20},
  btnCloseModal: {
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  txtBtnCloseModal: {fontSize: 20},
});

export default styles;
